.onLoad <- function(lib, pkg) {
    Sys.setenv(TZ = "GMT")
    Sys.setenv(R_HOCR_DATA_DIR=paste(lib, pkg, "data", sep="/"))
    cat("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n")
    cat("TO BEGIN A PROCESSING, \n")
    cat("1. Move to working directory (setwd(PATH)),\n")
    cat("2. Create a file directories.for.HyperSAS.dat and\n  ")
    cat("   put in it the names of the directories where data\n")
    cat("   files can be found (one by line).\n")
    cat("   At the end of each directory, add either STATION or TRANSIT\n")
    cat("   to indicate if the data in the folder are for a single station\n")
    cat("   or a collection of Rrs spectra along the ship transit.\n")
    cat("3. Create an ASCII file named cast.info.dat, which shall include \n")
    cat("   the ancillary data needed for the data processing, i.e.:  \n")
    cat("   Year,Day,Time,Dphi,ThetaV,Windspeed,Wind.units,\n")
    cat("   quantile.prob,tilt.max,NIR.CORRECTION,good.\n")
    cat("   Read the help for more details.\n")
    cat("4. Type HyperSAS.go() in the working directory. \n")
    cat("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n")
  }
